### ISSUE TITLE
[BUG] Make not sense when i tried to get non-existent array index 

### ISSUE THREAD

**Issue by manujoz** [Bnaya/objectbuffer#159]
When I try to access an index of an array that does not exist I get an error that says "it doesn't make sense" and it's logical, but I think it would be good to return an "undefined" instead of an error since in many cases in javascript we want to check if the array index has something just trying to access it.

Example:
```javascript
const object = {
  name: "Manu",
  surname: "Overa",
  cars: [],
}

let data = createObjectBuffer(
  {},
  // size in bytes
  75497472,
  object ,
  { useSharedArrayBuffer: true }
);

if(!data.cars[0]) {
  // Error: NOT MAKES SENSE
}
```

I understand the error, when trying to access an index that is greater than the length of the array, it obviously doesn't make sense. But in javascript this type of conditional is very prevalent and I think an error should not be returned when trying to access an undefined index.

**Comment by Bnaya** [comment]
Hey @manujoz 
Thank you for reporting this bug!
I will look into it

**Comment by Bnaya** [comment]
Update:
This issue is fixed on master,
I'm working on automating releases (using changesets) and then you will be able to use the latest version

**Comment by Bnaya** [comment]
I've created a sandbox with your code using the most recent objectbuffer version
https://codesandbox.io/s/objectbuffer-issue-159-pylyk
Let me know if it solves your problems
Thanks!

**Comment by Bnaya** [comment]
This bug should be fixed in the recent release
If this bug persists please open a new bug,
Thanks!
