### ISSUE TITLE
Would it make sense to support WeakMaps? 

### ISSUE THREAD

**Issue by LifeIsStrange** [Bnaya/objectbuffer#174]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections#weakmap_object
See also the analogue WeakSet.

(I've seen that you already implemented support for WeakReferences btw)

**Comment by Bnaya** [comment]
You mean you would want to save WeakMaps/Sets to the objectbuffer?
I'm not sure if it's possible.
WeakReferences as in use internally as part of the memory reclaiming, but you can't save them into an objectbuffer.

Unless I'm missing something :)
I would love to hear more about your usecase
