### ISSUE TITLE
How to reliably estimate size without too much overhead?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [Bnaya/objectbuffer#182]
I need to store a `Map<string, object>` in an object-backed buffer.

I tried [using](https://www.npmjs.com/package/object-sizeof) `object-sizeof` to estimate the size of that map. Judging from the implementation, internally, it converts to `Object.fromEntries()` to get such an estimate; then, it stringifies the object and counts the bytes in the resulting string.

Then I do this:

```
        // this._map: Map<string, NestedObjectType>    

        let bufferSize = Math.round(sizeof(this._map) + 128); // some padding for object wrapper

        if (bufferSize % 8 !== 0) {
            bufferSize += 8 - (bufferSize % 8);
        }

        const result = createObjectBuffer(bufferSize, {
            map: this._map,
        });
```

However, I am receiving an `OutOfMemoryError`. 

The whole reason of considering this library is potential memory savings - there can be multiple such objects, potentially of many megabytes in size. Is there a way to reliably estimate the size of an object?

Is there a caveat for `Map` specifically and should I switch to objects instead?

@Bnaya thank you for the library and hoping to find answers!

**Comment by wh1t3cAt1k** [comment]
I confirm that using `Object.fromEntries()` instead of a Map() results in the same error...

![image](https://user-images.githubusercontent.com/5159662/229923236-6335470b-0cfb-4ccb-9a58-c23484e9eca3.png)

My estimated buffer size with a factor of 1.25:

![image](https://user-images.githubusercontent.com/5159662/229923407-8ba9b549-792d-4c5c-9dc0-b496029f5113.png)

Still fails, as you can see from the first screenshot...

Is it a multiplicative factor or a completely unpredictable one? What is your empirical value?

**Comment by Bnaya** [comment]
Hey Pavel :)

If you may, you can share with me some of your data and i can take a look.
maybe there's a bug that makes it use more memory than it should,
but I'm sorry in advance, but there is no reliable way, from various reasons.
And I'm aiming to be compatible in anyway to 3rd party libs like `object-sizeof` not to mimic, nor to reason about their logic
My library is a very different animal.

And i don't think objectbuffer will help you to save memory compare to using native js objects

**Comment by Bnaya** [comment]
Feel free to open a new issue if you have any additional questions!
